"""EvalFP — Comunicación empresarial y atención al cliente · 0437 · Gestión Administrativa
Decreto 251/2011, de 12/08/2011, por el que se establece el currículo del ciclo formativo de grado medio de Gestión Administrativa en Castilla-La Mancha (DOCM 22/08/2011)
RA y CE literales del anexo de currículo del decreto de Castilla-La Mancha (DOCM).
Duración: 130 h · 4 h/semana · 1º GA.
"""
MODULO = {
    "nombre":"Comunicación empresarial y atención al cliente","codigo":"0437","abrev":"CEAC",
    "ciclo":"Gestión Administrativa","ciclo_clave":"GA","ciclo_nivel":"CFGM",
    "curso":"1º GA","horas_sem":4,"total_horas":130,"anno":"2026-2027","eval_count":3,
    "decreto":"Decreto 251/2011, de 12/08/2011, por el que se establece el currículo del ciclo formativo de grado medio de Gestión Administrativa en Castilla-La Mancha (DOCM 22/08/2011)",
}
UTS = [
    {"id":"UT1","nombre":"La comunicación en la empresa","horas":16,"eval":1,"tags":"Elementos del proceso · Barreras · Estructura organizativa · Organigramas · Flujos de información · Imagen corporativa"},
    {"id":"UT2","nombre":"Comunicación oral y telefónica","horas":17,"eval":1,"tags":"Atención telefónica · Centralita · Protocolo · Comunicación no verbal · Presentaciones · Videoconferencia"},
    {"id":"UT3","nombre":"Comunicación escrita","horas":19,"eval":1,"tags":"Cartas comerciales · Informes · Correo electrónico · Documentos de la Administración · Registro de entrada y salida"},
    {"id":"UT4","nombre":"Archivo y gestión documental","horas":17,"eval":2,"tags":"Sistemas de clasificación · Archivo físico e informático · Bases de datos · Protección de datos · Conservación y destrucción"},
    {"id":"UT5","nombre":"La clientela y sus necesidades","horas":15,"eval":2,"tags":"Tipos de clientela · Motivaciones de compra · Fases de la atención · Técnicas de venta"},
    {"id":"UT6","nombre":"Quejas, consultas y reclamaciones","horas":17,"eval":2,"tags":"Normativa de consumo · Hoja de reclamaciones · Mediación y arbitraje · OMIC · Juntas arbitrales"},
    {"id":"UT7","nombre":"Marketing e imagen de empresa","horas":12,"eval":3,"tags":"Marketing mix · Publicidad y promoción · Fidelización · Imagen de marca · Redes sociales"},
    {"id":"UT8","nombre":"Calidad en la atención a la clientela","horas":17,"eval":3,"tags":"Estándares e indicadores · Certificación · Tratamiento de anomalías · Mejora continua"},
]
RAS = [
    {"id":"RA1","pond":12,"nombre":"Selecciona técnicas de comunicación, relacionándolas con la estructura e imagen de la empresa y los flujos de información existentes en ella."},
    {"id":"RA2","pond":13,"nombre":"Transmite información de forma oral, vinculándola a los usos y costumbres socioprofesionales habituales en la empresa."},
    {"id":"RA3","pond":15,"nombre":"Transmite información escrita, aplicando las técnicas de estilo a diferentes tipos de documentos propios de la empresa y de la Administración Pública."},
    {"id":"RA4","pond":13,"nombre":"Archiva información en soporte papel e informático, reconociendo los criterios de eficiencia y ahorro en los trámi - tes administrativos."},
    {"id":"RA5","pond":12,"nombre":"Reconoce necesidades de posible clientela aplicando técnicas de comunicación."},
    {"id":"RA6","pond":13,"nombre":"Atiende consultas, quejas y reclamaciones de posible clientela aplicando la normativa vigente en materia de con - sumo."},
    {"id":"RA7","pond":9,"nombre":"Potencia la imagen de empresa reconociendo y aplicando los elementos y herramientas del marketing."},
    {"id":"RA8","pond":13,"nombre":"Aplica procedimientos de calidad en la atención a la clientela identificando los estándares establecidos."},
]
ASIGNACIONES = [
    ("UT1","RA1",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9"]),
    ("UT2","RA2",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
    ("UT3","RA3",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11"]),
    ("UT4","RA4",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
    ("UT5","RA5",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9"]),
    ("UT6","RA6",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
    ("UT7","RA7",["CR1","CR2","CR3","CR4","CR5","CR6","CR7"]),
    ("UT8","RA8",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
]
EVAL_RAS = {1:["RA1","RA2","RA3"], 2:["RA4","RA5","RA6"], 3:["RA7","RA8"]}
DUAL_RA = None
RA_INSTRUMENTOS = {
    "RA1":["examen","practica"],
    "RA2":["practica","examen"],
    "RA3":["practica","examen"],
    "RA4":["practica","examen"],
    "RA5":["practica","examen"],
    "RA6":["examen","practica"],
    "RA7":["examen","practica"],
    "RA8":["practica","examen"],
}
CES = {
    "RA1":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha reconocido la necesidad de comunicación entre las personas.",
        "Se ha distinguido entre comunicación e información.",
        "Se han distinguido los elementos y procesos que intervienen en la comunicación.",
        "Se han reconocido los obstáculos que pueden existir en un proceso de comunicación.",
        "Se ha determinado la mejor forma y actitud a la hora de presentar el mensaje.",
        "Se han identificado los conceptos de imagen y cultura de la empresa.",
        "Se han diferenciado los tipos de organizaciones y su organigrama funcional.",
        "Se han distinguido las comunicaciones internas y externas y los flujos de información dentro de la empresa.",
        "Se ha seleccionado el destinatario y el canal adecuado para cada situación.",
    ], start=1)],
    "RA2":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han identificado los principios básicos a tener en cuenta en la comunicación verbal.",
        "Se ha identificado el protocolo de comunicación verbal y no verbal en las comunicaciones presenciales y no pre - senciales.",
        "Se han tenido en cuenta las costumbres socioculturales y los usos empresariales.",
        "Se ha identificado al interlocutor, observando las debidas normas de protocolo, adaptando su actitud y conversa - ción a la situación de la que se parte.",
        "Se ha elaborado el mensaje verbal, de manera concreta y precisa, valorando las posibles dificultades en su trans - misión.",
        "Se ha utilizado el léxico y expresiones adecuados al tipo de comunicación y a las personas interlocutoras.",
        "Se ha presentado el mensaje verbal elaborado utilizando el lenguaje no verbal más adecuado.",
        "Se han utilizado equipos de telefonía e informáticos aplicando las normas básicas de uso.",
        "Se ha valorado si la información es transmitida con claridad, de forma estructurada, con precisión, con cortesía, con respeto y sensibilidad.",
        "Se han analizado los errores cometidos y propuesto las acciones correctivas necesarias.",
    ], start=1)],
    "RA3":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han identificado los soportes para elaborar y transmitir los documentos: tipo de papel, sobres y otros.",
        "Se han identificado los canales de transmisión: correo convencional, correo electrónico, fax, mensajes cortos o similares.",
        "Se han diferenciado los soportes más apropiados en función de los criterios de rapidez, seguridad, y confidencia - lidad.",
        "Se ha identificado al destinatario observando las debidas normas de protocolo.",
        "Se han clasificado las tipologías más habituales de documentos dentro de la empresa según su finalidad.",
        "Se ha redactado el documento apropiado, cumpliendo las normas ortográficas y sintácticas en función de su fina - lidad y de la situación de partida.",
        "Se han identificado las herramientas de búsqueda de información para elaborar la documentación.",
        "Se han utilizado las aplicaciones informáticas de procesamiento de textos o autoedición.",
        "Se han cumplimentado los libros de registro de entrada y salida de correspondencia y paquetería en soporte in - formático y/o convencional.",
        "Se ha utilizado la normativa sobre protección de datos y conservación de documentos establecidos para las em - presas e instituciones públicas y privadas.",
        "Se han aplicado, en la elaboración de la documentación, las técnicas 3R (reducir, reutilizar, reciclar).",
    ], start=1)],
    "RA4":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha descrito la finalidad de organizar la información y los objetivos que se persiguen.",
        "Se han diferenciado las técnicas de organización de información que se pueden aplicar en una empresa o ins - titución, así como los procedimientos habituales de registro, clasificación y distribución de la información en las organizaciones.",
        "Se han identificado los soportes de archivo y registro y las prestaciones de las aplicaciones informáticas especí - ficas más utilizadas en función de las características de la información a almacenar.",
        "Se han identificado las principales bases de datos de las organizaciones, su estructura y funciones.",
        "Se ha determinado el sistema de clasificación, registro y archivo apropiados al tipo de documentos.",
        "Se han realizado árboles de archivos informáticos para ordenar la documentación digital.",
        "Se han aplicado las técnicas de archivo en los intercambios de información telemática (intranet, extranet, correo electrónico).",
        "Se han reconocido los procedimientos de consulta y conservación de la información y documentación y detectado los errores que pudieran producirse en él.",
        "Se han respetado los niveles de protección, seguridad y acceso a la información, así como la normativa vigente tanto en documentos físicos como en bases de datos informáticas.",
        "Se han aplicado, en la elaboración y archivo de la documentación, las técnicas 3R (reducir, reutilizar, reciclar).",
    ], start=1)],
    "RA5":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han desarrollado técnicas de comunicación y habilidades sociales que facilitan la empatía con la clientela en situaciones de atención/asesoramiento a la misma.",
        "Se han identificado las fases que componen el proceso de atención al cliente/consumidor/usuario a través de diferentes canales de comunicación.",
        "Se han reconocido los errores más habituales que se cometen en la comunicación con la clientela.",
        "Se ha identificado el comportamiento de la clientela.",
        "Se han analizado las motivaciones de compra o demanda de un servicio de la clientela.",
        "Se ha obtenido, en su caso, la información histórica del cliente o clienta.",
        "Se ha adaptado adecuadamente la actitud y discurso a la situación de la que se parte.",
        "Se ha observado la forma y actitud adecuadas en la atención y asesoramiento a un cliente en función del canal de comunicación utilizado.",
        "Se han distinguido las distintas etapas de un proceso comunicativo.",
    ], start=1)],
    "RA6":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han descrito las funciones del departamento de atención a la clientela en empresas.",
        "Se ha interpretado la comunicación recibida por parte de la clientela.",
        "Se han identificado los elementos de la queja/reclamación.",
        "Se han reconocido las fases que componen el plan interno de resolución de quejas/reclamaciones.",
        "Se ha identificado y localizado la información que hay que suministrar a la clientela.",
        "Se han utilizado los documentos propios de la gestión de consultas, quejas y reclamaciones.",
        "Se ha cumplimentado, en su caso, un escrito de respuesta utilizando medios electrónicos u otros canales de comunicación.",
        "Se ha reconocido la importancia de la protección de la persona consumidora.",
        "Se ha identificado la normativa en materia de consumo.",
        "Se han diferenciado los tipos de demanda o reclamación.",
    ], start=1)],
    "RA7":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha identificado el concepto de marketing.",
        "Se han reconocido las funciones principales del marketing.",
        "Se ha valorado la importancia del departamento de marketing.",
        "Se han diferenciado los elementos y herramientas básicos que componen el marketing.",
        "Se ha valorado la importancia de la imagen corporativa para conseguir los objetivos de la empresa.",
        "Se ha valorado la importancia de las relaciones públicas y la atención a la clientela para la imagen de la empresa.",
        "Se ha identificado la fidelización del cliente como un objetivo prioritario del marketing.",
    ], start=1)],
    "RA8":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han identificado los factores que influyen en la prestación del servicio a la clientela.",
        "Se han descrito las fases del procedimiento de relación con la clientela.",
        "Se han descrito los estándares de calidad definidos en la prestación del servicio.",
        "Se ha valorado la importancia de una actitud proactiva para anticiparse a incidencias en los procesos.",
        "Se han detectado los errores producidos en la prestación del servicio.",
        "Se ha aplicado el tratamiento adecuado en la gestión de las anomalías producidas.",
        "Se ha explicado el significado e importancia del servicio post-venta en los procesos comerciales.",
        "Se han definido las variables constitutivas del servicio post-venta y su relación con la fidelización de la clientela.",
        "Se han identificado las situaciones comerciales que precisan seguimiento y servicio post-venta.",
        "Se han descrito los métodos más utilizados habitualmente en el control de calidad del servicio post-venta, así como sus fases y herramientas.",
    ], start=1)],
}
