"""EvalFP — Ofimática y proceso de la información · 0649 · Administración y Finanzas
Horas y curso: Decreto 80/2024, de 05/11/2024 (DOCM núm. 218, de 11/11/2024), Anexo I-C.4º · RA y CE: Decreto 43/2013, de 25/07/2013 (DOCM núm. 148, de 01/08/2013), Anexo II
RA y CE literales del anexo de currículo del decreto de Castilla-La Mancha (DOCM).
Duración: 223 h · 7 h/semana · 1º AF.
"""
MODULO = {
    "nombre":"Ofimática y proceso de la información","codigo":"0649","abrev":"OPI",
    "ciclo":"Administración y Finanzas","ciclo_clave":"AF","ciclo_nivel":"CFGS",
    "curso":"1º AF","horas_sem":7,"total_horas":223,"anno":"2026-2027","eval_count":3,
    "decreto":"Horas y curso: Decreto 80/2024, de 05/11/2024 (DOCM núm. 218, de 11/11/2024), Anexo I-C.4º · RA y CE: Decreto 43/2013, de 25/07/2013 (DOCM núm. 148, de 01/08/2013), Anexo II",
}
UTS = [
    {"id":"UT1","nombre":"Equipos, aplicaciones y red","horas":24,"eval":1,"tags":"Instalación y actualización · Configuración · Seguridad · Copias de seguridad · Incidencias"},
    {"id":"UT2","nombre":"Mecanografía por ordenador","horas":29,"eval":1,"tags":"Teclado extendido · Escritura al tacto · Velocidad y precisión · Ergonomía"},
    {"id":"UT3","nombre":"Gestión de archivos y búsqueda de información","horas":32,"eval":1,"tags":"Estructura de carpetas · Nomenclatura · Búsqueda avanzada · Digitalización · Archivo electrónico"},
    {"id":"UT4","nombre":"Hoja de cálculo avanzada","horas":29,"eval":2,"tags":"Funciones · Referencias · Tablas dinámicas · Gráficos · Macros · Plantillas"},
    {"id":"UT5","nombre":"Procesador de textos avanzado","horas":24,"eval":2,"tags":"Estilos · Secciones · Índices · Combinar correspondencia · Formularios · Control de cambios"},
    {"id":"UT6","nombre":"Bases de datos","horas":23,"eval":2,"tags":"Tablas y relaciones · Consultas · Formularios · Informes · Importación y exportación"},
    {"id":"UT7","nombre":"Integración de información y multimedia","horas":15,"eval":3,"tags":"Vinculación e incrustación · Imagen · Audio y vídeo · Formatos · PDF"},
    {"id":"UT8","nombre":"Correo y agenda electrónica","horas":29,"eval":3,"tags":"Cuentas y firmas · Filtros y reglas · Calendario · Tareas · Netiqueta"},
    {"id":"UT9","nombre":"Presentaciones multimedia","horas":18,"eval":3,"tags":"Diseño · Plantillas corporativas · Animaciones · Notas del orador · Exposición"},
]
RAS = [
    {"id":"RA1","pond":11,"nombre":"Mantiene en condiciones óptimas de funcionamiento los equipos, aplicaciones y red, instalando y actualizando los componentes hardware y software necesarios."},
    {"id":"RA2","pond":13,"nombre":"Escribe textos alfanuméricos en un teclado extendido, aplicando las técnicas mecanográficas."},
    {"id":"RA3","pond":14,"nombre":"Gestiona los sistemas de archivos, buscando y seleccionando con medios convencionales e informáticos la información necesaria."},
    {"id":"RA4","pond":13,"nombre":"Elabora hojas de cálculo adaptadas a las necesidades que se planteen en el tratamiento de la información, aplicando las opciones avanzadas."},
    {"id":"RA5","pond":11,"nombre":"Elabora documentos de textos, utilizando las opciones avanzadas de un procesador de textos."},
    {"id":"RA6","pond":10,"nombre":"Utiliza sistemas de gestión de bases de datos adaptadas a las necesidades que se planteen en el tratamiento de la información administrativa, aplicando las opciones avanzadas."},
    {"id":"RA7","pond":7,"nombre":"Gestiona integradamente la información proveniente de diferentes aplicaciones así como archivos audiovisuales, utilizando programas y periféricos específicos."},
    {"id":"RA8","pond":13,"nombre":"Gestiona el correo y la agenda electrónica, utilizando aplicaciones específicas."},
    {"id":"RA9","pond":8,"nombre":"Elabora presentaciones multimedia de documentos e informes, utilizando aplicaciones específicas."},
]
ASIGNACIONES = [
    ("UT1","RA1",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8"]),
    ("UT2","RA2",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
    ("UT3","RA3",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11"]),
    ("UT4","RA4",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
    ("UT5","RA5",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8"]),
    ("UT6","RA6",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8"]),
    ("UT7","RA7",["CR1","CR2","CR3","CR4","CR5"]),
    ("UT8","RA8",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
    ("UT9","RA9",["CR1","CR2","CR3","CR4","CR5","CR6"]),
]
EVAL_RAS = {1:["RA1","RA2","RA3"], 2:["RA4","RA5","RA6"], 3:["RA7","RA8","RA9"]}
DUAL_RA = None
RA_INSTRUMENTOS = {
    "RA1":["practica","examen"],
    "RA2":["practica"],
    "RA3":["practica"],
    "RA4":["practica","examen"],
    "RA5":["practica","examen"],
    "RA6":["practica","examen"],
    "RA7":["practica"],
    "RA8":["practica"],
    "RA9":["practica","proyecto"],
}
CES = {
    "RA1":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han realizado pruebas de funcionamiento de los equipos informáticos.",
        "Se han comprobado las conexiones de los puertos de comunicación.",
        "Se han identificado los elementos básicos (hardware y software) de un sistema en red.",
        "Se han caracterizado los procedimientos generales de operaciones en un sistema de red.",
        "Se han utilizado las funciones básicas del sistema operativo.",
        "Se han aplicado medidas de seguridad y confidencialidad, identificando el programa cortafuegos y el antivirus.",
        "Se ha compartido información con otros usuarios de la red.",
        "Se han ejecutado funciones básicas de usuario (conexión, desconexión, optimización del espacio de almacenamiento, utilización de periféricos, comunicación con otros usuarios y conexión con otros sistemas o redes, entre otras).",
    ], start=1)],
    "RA2":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han organizado los elementos y espacios de trabajo.",
        "Se ha mantenido la postura corporal correcta.",
        "Se ha identificado la posición correcta de los dedos en las filas del teclado alfanumérico.",
        "Se han precisado las funciones de puesta en marcha del terminal informático.",
        "Se han empleado coordinadamente las líneas del teclado alfanumérico y las teclas de signos y puntuación.",
        "Se ha utilizado el método de escritura al tacto en párrafos de dificultad progresiva y en tablas sencillas.",
        "Se ha utilizado el método de escritura al tacto para realizar textos en inglés.",
        "Se ha mecanografiado con velocidad (mínimo 200 p.p.m.) y precisión (máximo una falta por minuto) con la ayuda de un programa informático.",
        "Se han aplicado las normas de presentación de los distintos documentos de texto.",
        "Se han localizado y corregido los errores mecanográficos, ortográficos y sintácticos.",
    ], start=1)],
    "RA3":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han detectado necesidades de información.",
        "Se han identificado y priorizado las fuentes de obtención de información.",
        "Se han elegido buscadores en Intranet y en Internet según criterios de rapidez y de opciones de búsqueda.",
        "Se han empleado herramientas Web 2.0 para obtener y producir información.",
        "Se han utilizado los criterios de búsqueda para restringir el número de resultados obtenidos.",
        "Se han aplicado sistemas de seguridad, protección, confidencialidad y restricción de la información.",
        "Se ha canalizado la información obtenida, archivándola y/o registrándola, en su caso.",
        "Se han organizado los archivos para facilitar la búsqueda posterior.",
        "Se ha actualizado la información necesaria.",
        "Se han cumplido los plazos previstos.",
        "Se han realizado copias de los archivos.",
    ], start=1)],
    "RA4":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han utilizado las prestaciones de la hoja de cálculo para realizar gestiones de tesorería, cálculos comerciales y otras operaciones administrativas.",
        "Se han diseñado y elaborado documentos con la hoja de cálculo.",
        "Se han relacionado y actualizado hojas de cálculo.",
        "Se han creado y anidado fórmulas y funciones.",
        "Se han establecido contraseñas para proteger celdas, hojas y libros.",
        "Se han obtenido gráficos para el análisis de la información.",
        "Se han empleado macros para la realización de documentos y plantillas.",
        "Se han importado y exportado hojas de cálculo creadas con otras aplicaciones y otros formatos.",
        "Se ha utilizado la hoja de cálculo como base de datos: formularios, creación de listas, filtrado, protección y ordenación de datos.",
        "Se han utilizado aplicaciones y periféricos para introducir textos, números, códigos e imágenes.",
    ], start=1)],
    "RA5":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han utilizado las funciones, prestaciones y procedimientos de los procesadores de textos y autoedición.",
        "Se han identificado las características de cada tipo de documento.",
        "Se han redactado documentos de texto con la destreza adecuada y aplicando las normas de estructura.",
        "Se han confeccionado plantillas adaptadas a los documentos administrativos tipo, incluyendo utilidades de combinación.",
        "Se han integrado objetos, gráficos, tablas, hojas de cálculo e hipervínculos, entre otros.",
        "Se han detectado y corregido los errores cometidos.",
        "Se ha recuperado y utilizado la información almacenada.",
        "Se han utilizado las funciones y utilidades que garanticen las normas de seguridad, integridad y confidencialidad de los datos.",
    ], start=1)],
    "RA6":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han ordenado y clasificado los datos de las bases de datos para presentar la información.",
        "Se han realizado consultas de bases de datos con criterios precisos.",
        "Se han realizado informes de bases de datos con criterios precisos.",
        "Se han realizado formularios con criterios precisos.",
        "Se han actualizado, fusionado y eliminado registros de las bases de datos.",
        "Se han relacionado las bases de datos con otras aplicaciones informáticas para desarrollar las actividades que así lo requieran.",
        "Se han protegido las bases de datos estableciendo niveles de seguridad.",
        "Se ha elaborado una base de datos adaptada a los requerimientos de la organización.",
    ], start=1)],
    "RA7":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han gestionado de forma integrada bases de datos, textos e imágenes, entre otros, importando y exportando datos provenientes de hojas de cálculo y obteniendo documentos compuestos de todas estas posibilidades.",
        "Se han seleccionado archivos audiovisuales de fuentes externas y se ha elegido el formato óptimo de éstos.",
        "Se ha creado y mantenido un banco propio de recursos audiovisuales.",
        "Se han personalizado los archivos audiovisuales en función del objetivo del documento que se quiere obtener.",
        "Se ha respetado la legislación específica en materia de protección de archivos audiovisuales.",
    ], start=1)],
    "RA8":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha utilizado la aplicación de correo electrónico.",
        "Se ha identificado el emisor, destinatario y contenido en un mensaje de correo.",
        "Se han aplicado filtros de protección de correo no deseado.",
        "Se ha canalizado la información a todos los implicados.",
        "Se ha comprobado la recepción del mensaje.",
        "Se han organizado las bandejas de entrada y salida.",
        "Se ha registrado la entrada o salida de correos.",
        "Se han impreso, archivado o eliminado los mensajes de correo.",
        "Se han aplicado las funciones y utilidades que ofrece la agenda electrónica como método de organización del departamento.",
        "Se han conectado y sincronizado agendas del equipo informático con dispositivos móviles.",
    ], start=1)],
    "RA9":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha realizado un análisis y selección de la información que se quiere incluir.",
        "Se han insertado distintos objetos (tablas, gráficos, hojas de cálculo, fotos, dibujos, organigramas, archivos de sonido y vídeo, entre otros).",
        "Se ha distribuido la información de forma clara y estructurada.",
        "Se han animado los objetos según el objetivo de la presentación.",
        "Se han creado presentaciones para acompañar exposiciones orales.",
        "Se han realizado presentaciones relacionadas con informes o documentación empresarial.",
    ], start=1)],
}
