"""EvalFP — Tratamiento Informático de la Información · 0440 · Gestión Administrativa
Horas y curso: Decreto 79/2024, de 05/11/2024 (DOCM núm. 218, de 11/11/2024), Anexo IC-1. 1º · RA y CE: Decreto 251/2011, de 12/08/2011 (DOCM núm. 164, de 22/08/2011), Anexo II
RA y CE literales del Anexo II del Decreto 251/2011 (DOCM); las horas y el curso son los del Decreto 79/2024, que modifica aquel currículo.
Duración: 233 h · 7 h/semana · 1º GA.
"""
MODULO = {
    "nombre":"Tratamiento Informático de la Información","codigo":"0440","abrev":"TII",
    "ciclo":"Gestión Administrativa","ciclo_clave":"GA","ciclo_nivel":"CFGM",
    "curso":"1º GA","horas_sem":7,"total_horas":233,"anno":"2026-2027","eval_count":3,
    "decreto":"Horas y curso: Decreto 79/2024, de 05/11/2024 (DOCM núm. 218, de 11/11/2024), Anexo IC-1. 1º · RA y CE: Decreto 251/2011, de 12/08/2011 (DOCM núm. 164, de 22/08/2011), Anexo II",
}
UTS = [
    {"id":"UT1","nombre":"Mecanografía por ordenador","horas":26,"eval":1,"tags":"Teclado extendido · Postura y ergonomía · Velocidad y precisión · Tutores mecanográficos"},
    {"id":"UT2","nombre":"Instalación de aplicaciones ofimáticas","horas":41,"eval":1,"tags":"Sistema operativo · Instalación y actualización · Licencias · Copias de seguridad · Antivirus"},
    {"id":"UT3","nombre":"Hoja de cálculo","horas":32,"eval":2,"tags":"Fórmulas y funciones · Formatos · Gráficos · Plantillas · Filtros y tablas dinámicas"},
    {"id":"UT4","nombre":"Procesador de textos","horas":32,"eval":2,"tags":"Formatos y estilos · Tablas · Combinar correspondencia · Plantillas · Índices"},
    {"id":"UT5","nombre":"Bases de datos ofimáticas","horas":27,"eval":2,"tags":"Tablas · Consultas · Formularios · Informes · Relaciones"},
    {"id":"UT6","nombre":"Imagen y vídeo digital","horas":24,"eval":3,"tags":"Periféricos de captura · Formatos · Edición básica · Integración en documentos"},
    {"id":"UT7","nombre":"Presentaciones multimedia","horas":21,"eval":3,"tags":"Diseño de diapositivas · Plantillas · Animaciones · Exposición · Accesibilidad"},
    {"id":"UT8","nombre":"Correo y agenda electrónica","horas":30,"eval":3,"tags":"Cuentas · Libreta de direcciones · Filtros · Calendario · Tareas · Netiqueta"},
]
RAS = [
    {"id":"RA1","pond":11,"nombre":"Procesa textos alfanuméricos en un teclado extendido aplicando las técnicas mecanográficas."},
    {"id":"RA2","pond":18,"nombre":"Instala y actualiza aplicaciones informáticas relacionadas con la tarea administrativa razonando los pasos a seguir en el proceso."},
    {"id":"RA3","pond":14,"nombre":"Elabora documentos y plantillas manejando opciones de la hoja de cálculo tipo."},
    {"id":"RA4","pond":13,"nombre":"Elabora documentos de textos utilizando las opciones de un procesador de textos tipo."},
    {"id":"RA5","pond":12,"nombre":"Realiza operaciones de manipulación de datos en bases de datos ofimáticas tipo."},
    {"id":"RA6","pond":10,"nombre":"Integra imágenes digitales y secuencias de vídeo, utilizando aplicaciones tipo y periféricos en documentos de la empresa."},
    {"id":"RA7","pond":9,"nombre":"Elabora presentaciones multimedia utilizando aplicaciones específicas."},
    {"id":"RA8","pond":13,"nombre":"Gestiona el correo y la agenda electrónica manejando aplicaciones especificas."},
]
ASIGNACIONES = [
    ("UT1","RA1",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11","CR12","CR13"]),
    ("UT2","RA2",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11","CR12","CR13","CR14","CR15","CR16","CR17","CR18","CR19","CR20","CR21"]),
    ("UT3","RA3",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11","CR12","CR13","CR14","CR15","CR16"]),
    ("UT4","RA4",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11","CR12","CR13","CR14","CR15","CR16"]),
    ("UT5","RA5",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11","CR12","CR13","CR14"]),
    ("UT6","RA6",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11","CR12"]),
    ("UT7","RA7",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11"]),
    ("UT8","RA8",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11","CR12","CR13","CR14","CR15"]),
]
EVAL_RAS = {1:["RA1","RA2"], 2:["RA3","RA4","RA5"], 3:["RA6","RA7","RA8"]}
DUAL_RA = None
RA_INSTRUMENTOS = {
    "RA1":["practica","examen"],
    "RA2":["practica","examen"],
    "RA3":["practica","examen"],
    "RA4":["practica","examen"],
    "RA5":["practica","examen"],
    "RA6":["practica","examen"],
    "RA7":["practica","proyecto"],
    "RA8":["practica","examen"],
}
CES = {
    "RA1":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha identificado la composición y estructura de un teclado extendido.",
        "Se han organizado los elementos y espacios de trabajo.",
        "Se ha mantenido la posición corporal correcta.",
        "Se ha identificado la posición correcta de los dedos en las filas del teclado alfanumérico.",
        "Se han precisado las funciones de puesta en marcha del terminal informático.",
        "Se han empleado coordinadamente las líneas del teclado alfanumérico y las teclas y signos de puntuación: domi - nante, superiores e inferiores.",
        "Se ha aplicado con rapidez y de forma precisa el funcionamiento de las teclas auxiliares: mayúsculas, signos ortográficos, numéricos, interrogativos y admirativos, tabuladores u otras.",
        "Se ha utilizado el método de escritura al tacto en párrafos de dificultad progresiva y en tablas sencillas.",
        "Se ha utilizado el método de escritura al tacto para realizar textos en inglés.",
        "Se ha controlado la velocidad (mínimo de 200 p.p.m.) y la precisión (máximo una falta por minuto) con la ayuda de un programa informático.",
        "Se han aplicado las normas de presentación de los distintos documentos de texto.",
        "Se han localizado y corregido los errores mecanográficos.",
        "Se han utilizado mecanismos de protección, copias seguridad, confidencialidad de los datos y aprovechado la sinergia del trabajo en grupo.",
    ], start=1)],
    "RA2":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han identificado los distintos elementos de un ordenador.",
        "Se han utilizado con eficiencia los distintos periféricos.",
        "Se ha configurado el sistema operativo en función de las necesidades de las aplicaciones a utilizar, el usuario a utilizarlo y características del entorno trabajo.",
        "Se han identificado las utilidades de intercambio de información entre programas y dentro del mismo programa.",
        "Se ha utilizado las herramientas de guardado, recuperación y protección de información limitando y dando distin - tos permisos a distintos usuarios, utilizando contraseñas, antivirus, firewire,...",
        "Se han creado directorios y subdirectorios que permitan un uso racional, organizado y eficiente de la informa - ción.",
        "Se maneja con eficiencia y seguridad las potencialidades del explorador de archivos.",
        "Se utilizan las herramientas del sistema para mantener al ordenador en un estado óptimo de uso: desfragmenta - dor, comprobación errores, antivirus, copias seguridad, restaurar sistema, programar tareas, firewire, antispam,…",
        "Se utiliza la ayuda para solucionar con independencia diversos problemas en el manejo de un sistema operativo.",
        "Se utilizan con destreza distintos sistemas operativos que permiten una adecuada adaptación a distintos entornos de trabajo.",
        "Se maneja las redes locales en el tratamiento de la información.",
        "Se utiliza y diferencia diversos navegadores de búsqueda de información interna y externa, valorando riesgo, ni - veles de seguridad y necesidad de actualización y de contratación de la información buscada.",
        "Se han identificado los requisitos mínimos y óptimos para el funcionamiento de la aplicación.",
        "Se ha gestionado la impresora.",
        "Se han identificado y establecido las fases del proceso de instalación y actualización.",
        "Se han respetado las especificaciones técnicas del proceso de instalación.",
        "Se han configurado las aplicaciones según los criterios establecidos.",
        "Se han documentado las incidencias y el resultado final.",
        "Se han solucionado problemas en la instalación o integración con el sistema informático.",
        "Se han eliminado y/o añadido componentes de la instalación en el equipo.",
        "Se han respetado las licencias software y derechos de autor.",
    ], start=1)],
    "RA3":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han creado libros de hojas de cálculo, relacionando distintas partes de hojas y se ha guardado en el lugar apropiado según normas de organización y tipo de archivo.",
        "Se han utilizado los diversos tipos de datos y referencia para celdas, rangos, hojas y libros.",
        "Se han utilizado títulos representativos, encabezados, pies de página y otros aspectos de configuración y formato del documento en las hojas de cálculo, de acuerdo con las necesidades de la actividad a desarrollar o al documento a presentar.",
        "Se han aplicado fórmulas y funciones con precisión, anidándolas si es necesario.",
        "Se comprueban los resultados obtenidos con los esperados.",
        "Se actualizan las hojas de cálculo en función de las nuevas finalidades o datos de entrada aprovechando las ven - tajas de recálculo.",
        "Se han generado y modificado gráficos de diferentes tipos de manera eficiente.",
        "Se han empleado macros para la realización de documentos y plantillas.",
        "Se han importado y exportado hojas de cálculo creadas con otras aplicaciones y en otros formatos.",
        "Se ha utilizado la hoja de cálculo como base de datos: formularios, creación de listas, filtrado, protección y orde - nación de datos.",
        "Se ha utilizado aplicaciones y periféricos para introducir textos, números, códigos e imágenes.",
        "Se ha configurado, ajustado el área de visualización y de impresión según las necesidades.",
        "Se han utilizado mecanismos de protección, copias seguridad, confidencialidad de los datos y aprovechado la sinergia del trabajo en grupo.",
        "Se utiliza la ayuda del programa, el asistente de funciones para solucionar dudas, problemas planteados o sur - gidos.",
        "Se aplica las hojas de cálculo en la elaboración de cálculos relativos a otros módulos: facturas, presupuestos, préstamos, créditos, tesorería, retenciones, horas trabajadas,…",
        "Se defiende en más de un programa de hoja de cálculo que convivan en el mercado, aumentando la flexibilidad y adaptación a la realidad del entorno empresarial.",
    ], start=1)],
    "RA4":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha aplicado una postura correcta y configurado elementos que mitigan la fatiga visual.",
        "Se ha identificado y/o configurado el entorno de trabajo: barras herramientas, comandos, idioma,…",
        "Se han utilizado las funciones, prestaciones y procedimientos de los procesadores de textos y autoedición.",
        "Se han identificado las características de cada tipo de documento.",
        "Se ha aplicado el color y formato fuente, párrafo acorde al tipo documento, organización, criterios medioambien - tales,…",
        "Se han redactado documentos de texto con la destreza adecuada y aplicando las normas de estructura y ortográ - ficas.",
        "Se han confeccionado plantillas adaptadas a los documentos administrativos tipo.",
        "Se han utilizado encabezados, pies de página, notas aclaratoria, corrector ortográficos, estilo periodístico, editor ecuaciones, organigramas, letras capitales, macros, búsquedas, reemplazar datos, autotexto, autocorrección, mar - cadores, saltos continuos o de página, ordenación datos, bordes, sombreados, tabulaciones, plantillas, numeración y viñetas.",
        "Se han integrado objetos, gráficos, tablas y hojas de cálculo, e hipervínculos entre otros.",
        "Se han detectado y corregido los errores cometidos.",
        "Se ha aplicado el resto de utilidades que presta la aplicación del procesador de textos con eficacia y oportuni - dad.",
        "Se ha recuperado, utilizado y si es necesario impreso la información almacenada.",
        "Se han utilizado las funciones y utilidades que garanticen las normas de seguridad, integridad y confidencialidad de los datos.",
        "Se utiliza la ayuda del programa para solucionar dudas, problemas planteados o surgidos.",
        "Se identifican las funciones e importancia del procesador de textos en la presentación de documentos relativos a este u otros módulos: cartas comerciales, instancias, presupuestos, notificaciones clientes/as – empleados/as, currículum, informes, organigramas,…",
        "Se defiende en más de un programa de procesador de texto que convivan en el mercado, aumentando la flexibi - lidad y adaptación a la realidad del entorno empresarial.",
    ], start=1)],
    "RA5":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha identificado el entorno de trabajo: barras herramientas, comandos, idioma,…",
        "Se han identificado los elementos de las bases de datos relacionales.",
        "Se han identificado las prestaciones de ordenación, presentación, importación y exportación de datos.",
        "Se han creado y utilizado las tablas de la base de datos (insertar, modificar y eliminar registros).",
        "Se han identificado las distintas clases de relaciones entre tablas y aplicado la correcta.",
        "Se han utilizado asistentes en la creación de consultas.",
        "Se han utilizado asistentes en la creación de formularios.",
        "Se han utilizado asistentes en la creación de informes.",
        "Se ha realizado búsqueda y filtrado sobre la información almacenada.",
        "Se han creado y utilizado base de datos ofimáticas para extraer, presentar e imprimir sólo cuando es necesario la información.",
        "Se han utilizado las funciones y utilidades que garanticen las normas de seguridad, integridad, confidencialidad de los datos, gestión de cuentas de usuarios y grupos.",
        "Se utiliza la ayuda del programa para solucionar dudas, problemas planteados o surgidos.",
        "Se identifican las funciones e importancia de la base de datos en su aplicación en este y otros módulos: gestión clientes/as, proveedores/as, trabajadores/as, almacén, combinar correspondencia,…",
        "Se defiende en más de un programa de base de datos que convivan en el mercado, aumentando la flexibilidad y adaptación a la realidad del entorno empresarial.",
    ], start=1)],
    "RA6":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han analizado los distintos formatos de imágenes.",
        "Se ha realizado la adquisición y presentación de imágenes con periféricos.",
        "Se ha trabajado con imágenes a diferentes resoluciones, según su finalidad.",
        "Se han importado y exportado imágenes en diversos formatos.",
        "Se han reconocido los elementos que componen una secuencia de video.",
        "Se han analizado los tipos de formatos y «codecs» más empleados.",
        "Se han importado y exportado secuencias de vídeo.",
        "Se han capturado secuencias de vídeo con recursos adecuados.",
        "Se han elaborado guías básicas de tratamiento de imágenes y vídeo.",
        "Se han integrado las imágenes y secuencias de video en los diversos documentos que utiliza en este u otros módulos.",
        "Se han utilizado las funciones y utilidades que garanticen las normas de seguridad, integridad y confidencialidad de los datos al guardar, recuperar y utilizar imágenes o videos.",
        "Se utiliza la ayuda del programa para solucionar dudas, problemas planteados o surgidos.",
    ], start=1)],
    "RA7":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han identificado las opciones básicas de las aplicaciones de presentaciones.",
        "Se reconocen los distintos tipos de vista asociados a una presentación.",
        "Se han aplicado y reconocido las distintas tipografías y normas básicas de composición, diseño y utilización del color.",
        "Se han diseñado plantillas de presentaciones.",
        "Se han creado presentaciones.",
        "Se han insertado diversos objetos, imágenes, tablas, sonidos,… en la presentación.",
        "Se ha presentado la información de forma persuasiva, cuidando aspectos de formato, estilo, fondos, tiempos de transición, intervalos, animaciones,…",
        "Se han utilizado las presentaciones como apoyo en los trabajos de este u otros módulos.",
        "Se utiliza la ayuda del programa para solucionar dudas, problemas planteados o surgidos.",
        "Se han utilizado las funciones y utilidades que garanticen las normas de seguridad, integridad y confidencialidad de los datos al guardar, recuperar y utilizar presentaciones.",
        "Se han utilizado periféricos para ejecutar presentaciones o imprimirlas.",
    ], start=1)],
    "RA8":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han descrito los elementos que componen un correo electrónico.",
        "Se han analizado las necesidades básicas de gestión de correo y agenda electrónica.",
        "Se ha manejado la dirección de correo, asunto, libreta de dirección u otras herramientas en el filtrado de correos no deseados.",
        "Se han configurado distintos tipos de cuentas de correo electrónico.",
        "Se han conectado y sincronizado agendas del equipo informático con dispositivos móviles.",
        "Se ha operado con la libreta de direcciones.",
        "Se ha gestionado usuarios, grupos de usuarios previamente verificados de otros registros de la empresa y se han subsanado posibles errores.",
        "Se ha trabajado con todas las opciones de gestión de correo electrónico (etiquetas, filtros, firmas, carpetas y otros).",
        "Se han utilizado opciones de agenda electrónica.",
        "Se clasifica y ordena la correspondencia electrónica en función de diversos criterios.",
        "Se actualizan los contactos en el momento en que se conoce sus variaciones.",
        "Se anexa archivos cuando así se requiera y se reenvía información a los miembros que sea necesario.",
        "Se elimina, copia, mueve y se imprime los correos en función de las necesidades de organización y respetando seguridad, integridad y confidencialidad en la información.",
        "Se ha utilizado el correo como apoyo en los trabajos de este u otros módulos y del trabajo en grupo.",
        "Se utiliza la ayuda del programa para solucionar dudas, problemas planteados o surgidos.",
    ], start=1)],
}
