"""EvalFP — Servicios de Red e Internet · 0375 · Administración de Sistemas Informáticos en Red (ASIR)
Decreto 200/2010, de 03/08/2010, currículo del ciclo de Administración de Sistemas Informáticos en Red en Castilla-La Mancha (DOCM, NID 2010/13389) · RA y CE literales del Anexo I
RA y CE literales del anexo de currículo del decreto de Castilla-La Mancha (DOCM).
Duración: 242 h · 6 h/semana · 2º ASIR.
"""
MODULO = {
    "nombre":"Servicios de Red e Internet","codigo":"0375","abrev":"SRI",
    "ciclo":"Administración de Sistemas Informáticos en Red (ASIR)","ciclo_clave":"ASIR","ciclo_nivel":"CFGS",
    "curso":"2º ASIR","horas_sem":6,"total_horas":242,"anno":"2026-2027","eval_count":3,
    "decreto":"Decreto 200/2010, de 03/08/2010, currículo del ciclo de Administración de Sistemas Informáticos en Red en Castilla-La Mancha (DOCM, NID 2010/13389) · RA y CE literales del Anexo I",
}
UTS = [
    {"id":"UT1","nombre":"Administra servicios de resolución de nombres","horas":32,"eval":1,"tags":""},
    {"id":"UT2","nombre":"Administra servicios de configuración automática","horas":26,"eval":1,"tags":""},
    {"id":"UT3","nombre":"Administra servidores Web","horas":32,"eval":1,"tags":""},
    {"id":"UT4","nombre":"Administra servicios de transferencia de archivos","horas":32,"eval":2,"tags":""},
    {"id":"UT5","nombre":"Administra servidores de correo electrónico","horas":36,"eval":2,"tags":""},
    {"id":"UT6","nombre":"Administra servicios de mensajería instantánea","horas":29,"eval":3,"tags":""},
    {"id":"UT7","nombre":"Administra servicios de audio","horas":26,"eval":3,"tags":""},
    {"id":"UT8","nombre":"Administra servicios de vídeo","horas":29,"eval":3,"tags":""},
]
RAS = [
    {"id":"RA1","pond":13,"nombre":"Administra servicios de resolución de nombres, analizándolos y garantizando la seguridad del servicio."},
    {"id":"RA2","pond":11,"nombre":"Administra servicios de configuración automática, identificándolos y verificando la correcta asignación de los parámetros."},
    {"id":"RA3","pond":13,"nombre":"Administra servidores Web aplicando criterios de configuración y asegurando el funcionamiento del servicio."},
    {"id":"RA4","pond":13,"nombre":"Administra servicios de transferencia de archivos asegurando y limitando el acceso a la información."},
    {"id":"RA5","pond":15,"nombre":"Administra servidores de correo electrónico, aplicando criterios de configuración y garantizando la seguridad del servicio."},
    {"id":"RA6","pond":12,"nombre":"Administra servicios de mensajería instantánea, noticias y listas de distribución, verificando y asegurando el acceso de los usuarios."},
    {"id":"RA7","pond":11,"nombre":"Administra servicios de audio identificando las necesidades de distribución y adaptando los formatos."},
    {"id":"RA8","pond":12,"nombre":"Administra servicios de vídeo identificando las necesidades de distribución y adaptando los formatos."},
]
ASIGNACIONES = [
    ("UT1","RA1",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
    ("UT2","RA2",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8"]),
    ("UT3","RA3",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
    ("UT4","RA4",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10"]),
    ("UT5","RA5",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9","CR10","CR11"]),
    ("UT6","RA6",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9"]),
    ("UT7","RA7",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8"]),
    ("UT8","RA8",["CR1","CR2","CR3","CR4","CR5","CR6","CR7","CR8","CR9"]),
]
EVAL_RAS = {1:["RA1","RA2","RA3"], 2:["RA4","RA5"], 3:["RA6","RA7","RA8"]}
DUAL_RA = None
RA_INSTRUMENTOS = {
    "RA1":["examen","practica"],
    "RA2":["examen","practica"],
    "RA3":["examen","practica"],
    "RA4":["examen","practica"],
    "RA5":["examen","practica"],
    "RA6":["examen","practica"],
    "RA7":["examen","practica"],
    "RA8":["examen","practica"],
}
CES = {
    "RA1":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han identificado y descrito escenarios en los que surge la necesidad de un servicio de resolución de nombres.",
        "Se han clasificado los principales mecanismos de resolución de nombres.",
        "Se ha descrito la estructura, nomenclatura y funcionalidad de los sistemas de nombres jerárquicos.",
        "Se han instalado y configurado servicios jerárquicos de resolución de nombres.",
        "Se ha preparado el servicio para reenviar consultas de recursos externos a otro servidor de nombres.",
        "Se ha preparado el servicio para almacenar y distribuir las respuestas procedentes de otros servidores.",
        "Se han añadido registros de nombres correspondientes a una zona nueva, con opciones relativas a servidores de correo y alias.",
        "Se han implementado soluciones de servidores de nombres en direcciones «ip» dinámicas.",
        "Se han realizado transferencias de zona entre dos o más servidores.",
        "Se han documentado los procedimientos de instalación y configuración.",
    ], start=1)],
    "RA2":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han reconocido los mecanismos automatizados de configuración de los parámetros de red y las ventajas que proporcionan.",
        "Se han ilustrado los procedimientos y pautas que intervienen en una solicitud de configuración de los parámetros de red.",
        "Se han instalado servidores de configuración de los parámetros de red.",
        "Se ha preparado el servicio para asignar la configuración básica a los equipos de una red local.",
        "Se han configurado asignaciones estáticas y dinámicas.",
        "Se han integrado en el servicio opciones adicionales de configuración.",
        "Se han documentado los procedimientos realizados.",
        "Se han instalado servidores o clientes de sincronización horaria (NTP).",
    ], start=1)],
    "RA3":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han descrito los fundamentos y protocolos en los que se basa el funcionamiento de un servidor Web.",
        "Se han instalado y configurado servidores Web.",
        "Se ha ampliado la funcionalidad del servidor mediante la activación y configuración de módulos.",
        "Se han creado y configurado sitios virtuales.",
        "Se han configurado los mecanismos de autenticación y control de acceso del servidor.",
        "Se han obtenido e instalado certificados digitales.",
        "Se han establecido mecanismos para asegurar las comunicaciones entre el cliente y el servidor.",
        "Se han realizado pruebas de monitorización del servicio.",
        "Se han analizado los registros del servicio para la elaboración de estadísticas y la resolución de incidencias.",
        "Se ha elaborado documentación relativa a la instalación, configuración y recomendaciones de uso del servicio.",
    ], start=1)],
    "RA4":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha establecido la utilidad y modo de operación del servicio de transferencia de archivos.",
        "Se han instalado y configurado servidores de transferencia de archivos.",
        "Se han creado usuarios y grupos para acceso remoto al servidor.",
        "Se ha configurado el acceso anónimo.",
        "Se han establecido límites en los distintos modos de acceso.",
        "Se ha comprobado el acceso al servidor, tanto en modo activo como en modo pasivo.",
        "Se han realizado pruebas con clientes en línea de comandos y con clientes en modo gráfico.",
        "Se ha utilizado el navegador como cliente del servicio de transferencia de archivos.",
        "Se ha elaborado documentación relativa a la instalación, configuración y recomendaciones de uso del servicio.",
        "Se han identificado las posibilidades de intercambio de archivos entre iguales en la red.",
    ], start=1)],
    "RA5":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han descrito los diferentes protocolos que intervienen en el envío y recogida del correo electrónico.",
        "Se ha instalado y configurado un servidor de correo electrónico.",
        "Se han creado cuentas de usuario y verificado el acceso de las mismas.",
        "Se han establecido y aplicado métodos para impedir usos indebidos del servidor de correo electrónico.",
        "Se han instalado servicios para permitir la recogida remota del correo existente en los buzones de usuario.",
        "Se han usado clientes de correo electrónico para enviar y recibir correo desde las cuentas creadas en el servidor.",
        "Se han utilizado la firma digital y el correo cifrado.",
        "Se ha configurado el servidor de correo como un servicio seguro.",
        "Se ha elaborado documentación relativa a la instalación, configuración y recomendaciones de uso del servicio.",
        "Se identifican los mensajes de correo que corresponden a correo basura, fraudes, engaños, cadenas y virus informáticos.",
        "Se ha instalado y configurado un cliente de correo electrónico.",
    ], start=1)],
    "RA6":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se han descrito los servicios de mensajería instantánea, noticias y listas de distribución.",
        "Se ha instalado y configurado el servicio de mensajería instantánea.",
        "Se han utilizado clientes gráficos y de texto de mensajería instantánea.",
        "Se ha instalado y configurado el servicio de noticias.",
        "Se ha instalado y configurado el servicio de listas de distribución.",
        "Se han determinado el tipo de lista y los modos de acceso permitidos.",
        "Se han creado cuentas de usuario y verificado el acceso a los servicios de mensajería instantánea, noticias y listas de distribución.",
        "Se ha elaborado documentación relativa a la instalación, configuración y recomendaciones de uso de los servicios de mensajería instantánea, noticias y listas de distribución.",
        "Se han identificado servicios alternativos a los servicios de mensajería instantánea para la comunicación entre los usuarios.",
    ], start=1)],
    "RA7":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha descrito la funcionalidad del servicio de audio.",
        "Se ha instalado y configurado un servidor de distribución de audio.",
        "Se ha instalado y configurado el cliente para el acceso al servidor de audio.",
        "Se han reconocido y utilizado formatos de audio digital.",
        "Se han utilizado herramientas de reproducción de audio en el cliente.",
        "Se han utilizado servicios de audio a través del navegador.",
        "Se han utilizado técnicas de sindicación y suscripción de audio.",
        "Se ha elaborado documentación relativa a la instalación y administración del servidor de audio.",
    ], start=1)],
    "RA8":[{"id":f"CR{i}","texto":t} for i,t in enumerate([
        "Se ha descrito la funcionalidad del servicio de vídeo.",
        "Se ha instalado y configurado un servidor de vídeo.",
        "Se ha configurado el cliente para el acceso al servidor de vídeo.",
        "Se han reconocido y utilizado formatos de compresión de vídeo digital.",
        "Se han utilizado técnicas de sindicación y suscripción de vídeo.",
        "Se han descrito las características y protocolos utilizados en el servicio de videoconferencia.",
        "Se han instalado y configurado herramientas gráficas para realizar videoconferencia.",
        "Se han utilizado herramientas gráficas y navegadores para realizar videoconferencias.",
        "Se ha elaborado documentación relativa a la instalación y administración del servidor de vídeo y del servicio de videoconferencia.",
    ], start=1)],
}
